version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin123
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080